//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperBabyEntities : DbContext
    {
        public SuperBabyEntities()
            : base("name=SuperBabyEntities")
        {
        }

        public SuperBabyEntities(string Conn)
            : base(Conn)
        {
        }
    

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Baby> Babies { get; set; }
        public DbSet<TypeMaster> TypeMasters { get; set; }
        public DbSet<User_Reset_Password> User_Reset_Password { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<TimelineEntry> TimelineEntries { get; set; }
    }
}
