//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMaster
    {
        public TypeMaster()
        {
            this.TimelineEntries = new HashSet<TimelineEntry>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual ICollection<TimelineEntry> TimelineEntries { get; set; }
    }
}
